//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colmena.Vista.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Colmena.Vista.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fondoPresupuesto {
            get {
                object obj = ResourceManager.GetObject("fondoPresupuesto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;style.css&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;title&gt;Document&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///            &lt;div style=&quot;position: relative; left: 0; top: 0;&quot;&gt;
        ///            &lt;img src=&quot;Imagenes/fondoPresupuesto.jpeg&quot; class=&quot;back&quot; /&gt;
        ///            
        ///            &lt;div class=&quot;container infront&quot;&gt;
        ///     [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string presupuesto {
            get {
                return ResourceManager.GetString("presupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;style.css&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;title&gt;Document&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;position: relative; left: 0; top: 0;&quot;&gt;
        ///        &lt;img src=&quot;Imagenes/fondoPresupuesto.jpeg&quot; class=&quot;back&quot; /&gt;
        ///
        ///        &lt;div class=&quot;container infront&quot;&gt;
        ///            &lt;div class=&quot;cliente&quot; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string presupuestoModificado {
            get {
                return ResourceManager.GetString("presupuestoModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @import url(&apos;https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,700;1,400&amp;display=swap&apos;);
        ///*{
        /// font-family: &apos;Open Sans&apos;, sans-serif;
        ///}
        ///
        ///.back {
        ///            position: relative;
        ///            top: 0;
        ///            left: 0;
        ///        }
        ///
        ///.infront {
        ///            position: absolute;
        ///            top: 80px;
        ///            left: 80px;
        ///        }
        ///table th{
        ///    margin-bottom: 50px;
        ///}
        ///
        ///.tablageneral{
        ///    margin-bottom: 50px;
        ///}
        ///
        ///
        ///.tablasecundaria{
        ///        margin-bottom: 50px;
        ///
        ///}
        ///.round [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
